# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b415781691a850cc707251a30c6a81b2708169d406568a5e6d63d31e160e6fc2564a7c304588a1d9873123f6553ad49b4fea40bb4a107125976ea3d3c45cbc3

test:
  secret_key_base: 4ee5be6dce16b6c903202051d203349126a121c447fa107469319ba77bfa3f416e40d0bad6d813ebc0b4e72f73784db1a51eb9d10bb53c7e5a3efc8f35b93942

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
